services:
  - type: web
    name: devflow-backend
    runtime: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python init_db.py && gunicorn "wsgi:app" --bind 0.0.0.0:$PORT --workers 2 --access-logfile - --error-logfile -
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: src/app.py
      - key: FRONTEND_URL
        value: https://devflow-ops.vercel.app
      - key: JWT_SECRET_KEY
        value: 0250b697a44c73968abf5da0914603f2fa5b449892c1fec83bc60a28b43cd676
      - key: TOKEN_ENCRYPTION_KEY
        value: deaf651fbe3dee74a663707adcdd5bde
      - key: DATABASE_URL
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: AI_PROVIDER
        value: groq
      - key: PROMETHEUS_URL
        sync: false
      - key: PROMETHEUS_USERNAME
        sync: false
      - key: PROMETHEUS_PASSWORD
        sync: false
      - key: GRAFANA_URL
        sync: false
      - key: PYTHONPATH
        value: src
      - key: PYTHON_VERSION
        value: 3.11.9
    healthCheckPath: /health
    domains:
      - devflow-backend.onrender.com
