apiVersion: v1
kind: Config
current-context: minikube-docker
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://host.docker.internal:61064
  name: minikube-docker
users:
- user:
    client-certificate: /.minikube/profiles/minikube/client.crt
    client-key: /.minikube/profiles/minikube/client.key
  name: minikube-docker
contexts:
- context:
    cluster: minikube-docker
    user: minikube-docker
  name: minikube-docker
