import { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { FiEye, FiCheckCircle } from 'react-icons/fi';
import * as orchestrationService from '../../services/orchestrationService';
import { DataTable } from '../../components/Tables/DataTable';
import { LoadingSpinner } from '../../components/Common/LoadingSpinner';
import { NetworkError } from '../../components/Common/NetworkError';
import { EmptyState } from '../../components/Common/EmptyState';

export default function OrchestrationIncidents() {
  const navigate = useNavigate();
  const [incidents, setIncidents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const fetchIncidents = useCallback(async () => {
    try {
      const data = await orchestrationService.getIncidents();
      setIncidents(data);
      setError(null);
    } catch (err) {
      setError(err);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchIncidents(); }, [fetchIncidents]);

  const resolveIncident = async (id) => {
    try {
      await orchestrationService.resolveIncident(id);
      await fetchIncidents();
    } catch (err) {
      setError(err);
    }
  };

  const columns = [
    { key: 'incident_id', label: 'ID', style: { color: 'var(--text-secondary)' }, render: (row) => row.incident_id },
    { key: 'summary', label: 'Summary', render: (row) => <strong>{row.summary}</strong> },
    { key: 'severity', label: 'Severity', render: (row) => <span className={`badge ${row.severity === 'critical' ? 'danger' : row.severity === 'high' ? 'warning' : 'neutral'}`}>{row.severity}</span> },
    { key: 'category', label: 'Category', render: (row) => <span className="badge neutral">{row.category || 'N/A'}</span> },
    { key: 'repository', label: 'Repository', style: { color: 'var(--text-secondary)' }, render: (row) => row.repository || '—' },
    { key: 'status', label: 'Status', render: (row) => <span className={`badge ${row.status === 'resolved' ? 'success' : row.status === 'open' ? 'warning' : 'neutral'}`}>{row.status}</span> },
    { key: 'created_at', label: 'Created', style: { color: 'var(--text-secondary)' }, render: (row) => row.created_at ? new Date(row.created_at).toLocaleString() : '—' },
    {
      key: 'actions', label: 'Actions',
      render: (row) => (
        <div style={{ display: 'flex', gap: '0.5rem' }}>
          <button className="btn" style={{ padding: '0.4rem 0.8rem', fontSize: '0.8rem' }} onClick={() => navigate(`/orchestration/incidents/${row.incident_id}`)}>
            <FiEye size={14} /> View
          </button>
          {row.status !== 'resolved' && (
            <button className="btn btn-success" style={{ padding: '0.4rem 0.8rem', fontSize: '0.8rem' }} onClick={() => resolveIncident(row.incident_id)}>
              <FiCheckCircle size={14} /> Resolve
            </button>
          )}
        </div>
      ),
    },
  ];

  if (loading) return <LoadingSpinner />;
  if (error) return <NetworkError error={error} onRetry={fetchIncidents} />;
  if (!incidents.length) return <EmptyState message="No orchestration incidents found" />;

  return (
    <div>
      <div className="page-header">
        <div>
          <h1 className="page-title">Orchestration Incidents</h1>
          <p className="page-subtitle">Incidents generated by the orchestration engine from correlated DevOps events.</p>
        </div>
      </div>
      <DataTable columns={columns} data={incidents} />
    </div>
  );
}
