import sqlite3
conn = sqlite3.connect('../database/app.db')
c = conn.cursor()
c.execute("PRAGMA foreign_key_list(incident)")
print("Incident FKs:", c.fetchall())
c.execute("PRAGMA index_list(incident)")
print("Incident indices:", c.fetchall())
c.execute("PRAGMA foreign_key_list(connected_project)")
print("ConnectedProject FKs:", c.fetchall())
conn.close()
