apiVersion: v1
kind: Service
metadata:
  name: devflow-servicecl
  namespace: devflow
  labels:
    job: node-devflow
    app: devflow
spec:
  type: NodePort
  selector:
    app: devflow
  ports:
    - name: devflow-port
      port: 80
      nodePort: 30007
      targetPort: 5000
      protocol: TCP
